### ISSUE TITLE
Use ispy to play rtmp video ，the  video has no audio.

### ISSUE THREAD

**Issue by best4s** [ispysoftware/iSpy#42]
Use ispy to play rtmp video ，the  video has no audio.

The MPEG AAC Audio has some noise.
The Speex Audio is mute.

I can not fix the issue.Could you help to fix it ？

**Comment by best4s** [comment]
Problem: there is no sound or full noise in the RTMP push stream with ispy.

Description: using the latest version ispy receiving phone RTMP push flow, when the audio coding format for mp4a ispy there is sound wave, and noise, when audio coding format for SPX, sound module can be loaded in, and can be recorded, but no audio recording file resources, and can't use voice module in the play button.The same media streaming is fine with VLC, and it's okay for me to use ispy to record RTMP streams on the network.I don't know how to fix it.Anyone to help me?

**Comment by ispysoftware** [comment]
Hello do you have an rtmp url for me to test?

**Comment by best4s** [comment]
The rtmp url is  “    rtmp://www.ossrs.net:1935/live/55555    ”

You could test it .Thank you .

**Comment by ispysoftware** [comment]
Hello I fixed it, problem in our ffmpeg code. Will upload an update.

**Comment by best4s** [comment]
Thank you .sean tearney.

**Comment by best4s** [comment]
I still have the issue.Could you help me to test it ?
Before a media stream perfect solve the noise problem, there is another format of the media stream is no sound, test address is "www.ossrs.net:1935/123456789/123aaa 

" or "www.ossrs.net:1935/123456789/123bbb 

".I'm looking forward to your reply, thank you!

**Comment by ispysoftware** [comment]
hello i can't connect to that, did you mean http:// or rtsp:// ?
neither are working in VLC...
